Repository invertase/react-native-google-mobile-ads, pull requests merged in 2021-12, with the labels that each got.

#10 fix: incorrect module naming
  lib/AdsConsent.js
  lib/internal/GoogleAdsNativeEventEmitter.js
Labels: workflow: pending merge

#17 fix: banner ads not working on android
  android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsBannerAdViewManager.java
Labels: question, workflow: pending merge

#30 feat(ios)!: Google Mobile Ads SDK 8 w/new testDeviceIdentifiers vs testDevices
  .github/workflows/create_test_patches.yml
  docs/index.mdx
  ios/RNGoogleAds/RNGoogleAdsBannerViewManager.m
  ios/RNGoogleAds/RNGoogleAdsCommon.h
  ios/RNGoogleAds/RNGoogleAdsCommon.m
  ios/RNGoogleAds/RNGoogleAdsFullScreenContentDelegate.h
  ios/RNGoogleAds/RNGoogleAdsFullScreenContentDelegate.m
  ios/RNGoogleAds/RNGoogleAdsInterstitialDelegate.m
  ios/RNGoogleAds/RNGoogleAdsInterstitialModule.m
  ios/RNGoogleAds/RNGoogleAdsModule.m
  ios/RNGoogleAds/RNGoogleAdsRewardedDelegate.h
  ios/RNGoogleAds/RNGoogleAdsRewardedDelegate.m
  ios/RNGoogleAds/RNGoogleAdsRewardedModule.m
  lib/BannerAdSize.js
  lib/index.d.ts
  package.json
Labels: workflow: pending merge

#31 fix: rewarded ads crash & request configuration
  __tests__/googleAds.test.ts
  e2e/interstitial.e2e.js
  e2e/rewarded.e2e.js
  ios/RNGoogleAds/RNGoogleAdsModule.m
  ios/RNGoogleAds/RNGoogleAdsRewardedModule.m
  lib/ads/InterstitialAd.js
  lib/ads/RewardedAd.js
  lib/index.d.ts
  lib/index.js
  lib/validateAdRequestConfiguration.js
Labels: workflow: waiting for feedback, workflow: pending merge

#32 feat(android, sdks)!: update to the latest gms:play-services-ads:20.5.0
  android/build.gradle
  android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsBannerAdViewManager.java
  android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsCommon.java
  android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsEvent.java
  android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsInterstitialModule.java
  android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsModule.java
  android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsRewardedModule.java
  example/android/build.gradle
  ios/RNGoogleAds/RNGoogleAdsCommon.h
  ios/RNGoogleAds/RNGoogleAdsCommon.m
  lib/AdEventType.js
  lib/index.d.ts
  type-test.ts
Labels: workflow: waiting for feedback

#37 feat: replace banner v7 methods with v8 methods
  ios/RNGoogleAds/RNGoogleAdsBannerViewManager.m
Labels: workflow: pending merge

#39 refactor: eliminates require cycles, and some unused code
  .eslintignore
  .eslintrc.js
  .github/PULL_REQUEST_TEMPLATE.md
  example/e2e/init.js
  lib/ads/InterstitialAd.js
  lib/ads/RewardedAd.js
  lib/common/Base64.js
  lib/common/path.js
  lib/googleMobileAds.js
  lib/index.js
Labels: workflow: waiting for feedback, workflow: pending merge

#40 feat: expose native SDK initialize methods as new `initialize` API
  android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsModule.java
  docs/index.mdx
  ios/RNGoogleAds/RNGoogleAdsModule.m
  lib/googleMobileAds.js
  lib/index.d.ts
Labels: workflow: pending merge

#50 feat: smarter error logging
  android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsCommon.java
  android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsInterstitialModule.java
  android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsRewardedModule.java
  ios/RNGoogleAds/RNGoogleAdsCommon.m
Labels: workflow: pending merge
