Repository invertase/react-native-google-mobile-ads, pull requests merged in 2022-10, with the labels that each got.

#248 docs(expo): add expo app.json setup instructions
  docs/index.mdx
Labels: workflow: pending merge

#247 docs(ios,expo): how to enable static frameworks
  docs/index.mdx
Labels: workflow: waiting for feedback

#245 feat: allow load to be called again after error
  __tests__/interstitial.test.ts
  jest.setup.ts
  src/ads/MobileAd.ts
Labels: workflow: pending merge

#246 refactor: remove some unused code
  src/internal/constants.ts
  src/internal/registry/nativeModule.ts
Labels: workflow: pending merge

#252 docs(consent, android): added guide for Expo users
  docs/european-user-consent.mdx
Labels: workflow: pending merge, hacktoberfest-accepted

#257 fix(ios): correct typo in ios_config.sh
  ios_config.sh
Labels: workflow: pending merge

#261 fix(deps): android sdk 21.3.0 / ios sdk 9.12.0
  package.json
Labels: workflow: pending merge
